In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.datasets import load_wine

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score

from sklearn.metrics import confusion_matrix,classification_report

Tasks: 

●  Load the dataset using Pandas. 

●  Separate features and target. 

●  Split the data into training and testing sets. 

●  Train a KNN classifier with K=3. 

●  Predict the test set labels. 

●  Calculate the accuracy score. 

●  Display the Confusion Matrix. 

●  Generate the Classification Report

In [14]:
df=pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [15]:
x=df.drop('Species',axis=1)
y=df['Species']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
knn_model=Pipeline(
    steps=[
        ('scaler',StandardScaler()),
        ('knn',KNeighborsClassifier())
        
    ]
)
knn_model.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('knn', KNeighborsClassifier())])

In [17]:
predict=knn_model.predict(x_test)
predict

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [18]:
accuracy_score=accuracy_score(y_test,predict)
print('Accuracy:',accuracy_score)

Accuracy: 1.0

In [19]:
confusion_matrix=confusion_matrix(y_test,predict)
print('Confusion Matrix:\n',confusion_matrix)

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

In [20]:
report=classification_report(y_test,predict)
print('Classification Report:\n',report)

Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

# 2 . GridSearchCV for Customer Segmentation Prediction 
Dataset: Customer Personality Analysis 

Dataset Link:

https://www.kaggle.com/datasets/imakash3011/customer-personality-analysis 

Tasks: 

●  Create a customer response prediction problem using the Response column.

●  Handle missing values. 

●  Scale the numerical features.

●  Use GridSearchCV to tune: 
    ○  n_neighbors 

    ○  metric 

    ○  weights 

●  Report the best parameters. 

●  Compare tuned KNN with default KNN. 

●  Evaluate using:

     ○  Accuracy 

     ○  Precision 

     ○  Recall 

○  F1-score 
 
 
 
 
 
 
Optional  
 
Credit Card Defa

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.datasets import load_wine

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score

from sklearn.metrics import confusion_matrix,classification_report

from sklearn.model_selection import GridSearchCV

In [26]:
df=pd.read_csv('marketing_campaign.csv', sep='\t')
df.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [27]:
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [28]:
df['Income'].fillna(df['Income'].mean(), inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_25256\2923762628.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Income'].fillna(df['Income'].mean(), inplace=True)

In [29]:
df.isnull().sum()

ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64

In [32]:
x=df.select_dtypes(include=[np.number]).drop('Response',axis=1)
y=df['Response']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [34]:
pipeline=Pipeline(
    steps=[
        ('scaler',StandardScaler()),
        ('knn',KNeighborsClassifier())
        
    ]
)
pipeline.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('knn', KNeighborsClassifier())])

In [35]:
grid_params={
    'knn__n_neighbors': [3, 5, 7, 9],
    'knn__weights': ['uniform', 'distance'],
    'knn__p': [1, 2]
    
}
grid_search=GridSearchCV(pipeline,grid_params,cv=5)
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('knn', KNeighborsClassifier())]),
             param_grid={'knn__n_neighbors': [3, 5, 7, 9], 'knn__p': [1, 2],
                         'knn__weights': ['uniform', 'distance']})

In [36]:
best_params=grid_search.best_params_
print('Best Parameters:',best_params)

Best Parameters: {'knn__n_neighbors': 7, 'knn__p': 2, 'knn__weights': 'uniform'}

In [38]:
#Compare tuned KNN with default KNN.
knn_predict=grid_search.predict(x_test)
knn_accuracy=accuracy_score(y_test,knn_predict) 

default_knn = KNeighborsClassifier()
default_knn.fit(x_train, y_train)
predict_default = default_knn.predict(x_test)
default_accuracy = accuracy_score(y_test, predict_default)
print("Tuned KNN Accuracy:", knn_accuracy)
print("Default KNN Accuracy:", default_accuracy)

Tuned KNN Accuracy: 0.8526785714285714
Default KNN Accuracy: 0.8415178571428571

In [39]:
precision = precision_score(y_test, knn_predict)
recall = recall_score(y_test, knn_predict)
print("Precision:", precision)
print("Recall:", recall)

Precision: 0.56
Recall: 0.2028985507246377

In [40]:
#F1 score
from sklearn.metrics import f1_score
f1 = f1_score(y_test, knn_predict)
print("F1 Score:", f1)

F1 Score: 0.2978723404255319