In [24]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder,MinMaxScaler,OrdinalEncoder
from sklearn.linear_model import LogisticRegression

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [25]:
df=pd.read_csv("titanic_data_updated (1).csv")
df.sample(5)

     PassengerId Survived  Pclass  ...     Fare Cabin  Embarked
440          441      yes  second  ...  26.2500   NaN         S
857          858      yes   first  ...  26.5500   E17         S
785          786       no   third  ...   7.2500   NaN         S
205          206       no   third  ...  10.4625    G6         S
310          311      yes   first  ...  83.1583   C54         C

[5 rows x 12 columns]

In [26]:
df['Cabin'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Cabin
Non-Null Count  Dtype
--------------  -----
204 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB

In [27]:
df['Family_Size'] = df['SibSp'] + df['Parch'] + 1
df['Family_Size']=df['Cabin'].fillna("Missing")

df['Deck'] = df['Cabin'].astype(str).str[0]
df.sample(5)

     PassengerId Survived  Pclass  ... Embarked Family_Size  Deck
790          791       no   third  ...        Q     Missing     n
649          650      yes   third  ...        S     Missing     n
413          414       no  second  ...        S     Missing     n
854          855       no  second  ...        S     Missing     n
718          719       no   third  ...        Q     Missing     n

[5 rows x 14 columns]

In [28]:
df['Deck'].value_counts()

Deck
n    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [29]:
x=df.drop('Survived',axis=1)
y=df['Survived']

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [31]:
x_train

     PassengerId  Pclass  ... Family_Size Deck
331          332   first  ...        C124    C
733          734  second  ...     Missing    n
382          383   third  ...     Missing    n
704          705   third  ...     Missing    n
813          814   third  ...     Missing    n
..           ...     ...  ...         ...  ...
106          107   third  ...     Missing    n
270          271   first  ...     Missing    n
860          861   third  ...     Missing    n
435          436   first  ...     B96 B98    B
102          103   first  ...         D26    D

[712 rows x 13 columns]

In [32]:
mean_age=x_train['Age'].mean()
std_age=x_train['Age'].std()

x_train['Z_score']=(x_train['Age']-mean_age)/std_age
musk=(abs(x_train['Z_score'])>3)

x_train=x_train[musk]
y_train=y_train[musk]

fare_Q1=x_train['Fare'].quantile(0.25)
fare_Q3=x_train['Fare'].quantile(0.75)


IQR=fare_Q3-fare_Q1

minimum=max(0, fare_Q1-1.5*IQR)
maximum=fare_Q3+1.5*IQR

x_train['Fare']=x_train['Fare'].clip(minimum,maximum)

C:\Users\user\AppData\Local\Temp\ipykernel_28408\201335385.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train['Fare']=x_train['Fare'].clip(minimum,maximum)

In [33]:
p1=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler())
])
p2=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('scaler',MinMaxScaler())
])
p3=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore'))

])
categorical_cols=[['third','second','first']]

p4=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OrdinalEncoder(categories=categorical_cols)),
    ('scaler',MinMaxScaler())
])
preprocessor=ColumnTransformer(transformers=[
    ('pipeline1',p1,['Age']),
    ('pipeline2',p2,['Fare','Family_Size']),
    ('pipeline3',p3,['Sex']),
    ('pipeline4',p4,['Pclass'])
])
preprocessor

ColumnTransformer(transformers=[('pipeline1',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['Age']),
                                ('pipeline2',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Fare', 'Family_Size']),
                                ('pipeline3',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Sex']),
                                ('pipeline4',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OrdinalEncoder(categories=[['third',
                                                                              'second',
                                                                              'first']])),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Pclass'])])

In [34]:
le=LabelEncoder()
y_train=le.fit_transform(y_train)
y_test=le.fit_transform(y_test)

In [35]:
lr_model=Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('model',LogisticRegression(class_weight='balanced',max_iter=1000))
    ]
)
lr_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('pipeline1',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age']),
                                                 ('pipeline2',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Fare', 'Family_Size']),
                                                 ('pipeline3',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(str...
                                                                  ('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Sex']),
                                                 ('pipeline4',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['third',
                                                                                               'second',
                                                                                               'first']])),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Pclass'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [37]:
lr_model.fit(x_train,y_train)

lr_model['model'].coef_
lr_model['model'].intercept_
lr_model['model'].classes_

ValueError: could not convert string to float: 'A23'

In [38]:
x_test

     PassengerId  Pclass  ... Family_Size Deck
709          710   third  ...     Missing    n
439          440  second  ...     Missing    n
840          841   third  ...     Missing    n
720          721  second  ...     Missing    n
39            40   third  ...     Missing    n
..           ...     ...  ...         ...  ...
433          434   third  ...     Missing    n
773          774   third  ...     Missing    n
25            26   third  ...     Missing    n
84            85  second  ...     Missing    n
10            11   third  ...          G6    G

[179 rows x 13 columns]

In [39]:
y_pred=lr_model.predict(x_test)
lr_model.predict_proba(x_test)

AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'

In [40]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)
precision=accuracy_score(y_test,y_pred)
print(precision)
recall=accuracy_score(y_test,y_pred)
print(recall)

NameError: name 'y_pred' is not defined