# ML Assignment 02
### Dataset: House Price Prediction Dataset
### Total Marks: 100

---

## Exam Instructions:
1. প্রথমে নিচের cell এ নিজের **নাম** এবং কোর্সে registration করা **ইমেইল** দিবে
2. Question wise numbering করে Text cell রাখবে এবং এর নিচে Code cell থাকবে, চেষ্টা করবে একটি code cell এ একটি question উত্তর দেওয়ার
3. Google Colab এর মধ্যে কোডগুলো করবে
4. এবং সেই ফাইলটি **'Anyone with the link' & 'View' Access** দিয়ে ফাইলটির Shareable Link টি সাবমিট করবে

---

**Question Dataset Link:** https://www.kaggle.com/datasets/prokshitha/home-value-insights

## Student Information

In [2]:
# Fill in your information
name = ""           # Write your full name here
email = ""          # Write your registered email here

print(f"Name  : {name}")
print(f"Email : {email}")

Name  :
Email :

---
## Question 1 (10 Marks)

Load the House Price dataset and display:
- Dataset shape
- First 10 rows
- 5 random samples

In [3]:
# Question 1
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv("house_price_regression_dataset.csv")
print(df)

     Square_Footage  Num_Bedrooms  ...  Neighborhood_Quality   House_Price
0              1360             2  ...                     5  2.623829e+05
1              4272             3  ...                     6  9.852609e+05
2              3592             1  ...                     9  7.779774e+05
3               966             1  ...                     8  2.296989e+05
4              4926             2  ...                     8  1.041741e+06
..              ...           ...  ...                   ...           ...
995            3261             4  ...                    10  7.014940e+05
996            3179             1  ...                    10  6.837232e+05
997            2606             4  ...                     2  5.720240e+05
998            4723             5  ...                     7  9.648653e+05
999            3268             4  ...                     2  7.425993e+05

[1000 rows x 8 columns]

In [4]:
print(df.shape)

(1000, 8)

In [5]:
df.head(10)

   Square_Footage  Num_Bedrooms  ...  Neighborhood_Quality   House_Price
0            1360             2  ...                     5  2.623829e+05
1            4272             3  ...                     6  9.852609e+05
2            3592             1  ...                     9  7.779774e+05
3             966             1  ...                     8  2.296989e+05
4            4926             2  ...                     8  1.041741e+06
5            3944             5  ...                     8  8.797970e+05
6            3671             1  ...                     1  8.144279e+05
7            3419             1  ...                     1  7.034131e+05
8             630             3  ...                     8  1.738750e+05
9            2185             4  ...                     5  5.041765e+05

[10 rows x 8 columns]

In [6]:
df.sample(5)

     Square_Footage  Num_Bedrooms  ...  Neighborhood_Quality    House_Price
267            3475             1  ...                     7  731899.435616
760            2876             3  ...                    10  663568.512667
857            2688             2  ...                    10  601890.291909
231            1718             5  ...                     6  424712.551252
224            1456             1  ...                     6  297387.922484

[5 rows x 8 columns]

---
## Question 2 (10 Marks)

Handle missing values and perform feature engineering:
- Impute missing numerical values using `SimpleImputer` with mean strategy
- Impute missing categorical values using most frequent strategy
- Drop columns with more than 50% missing values
- Perform train-test split with `test_size=0.2` and `random_state=42`

Display the shape of final train and test sets.

In [7]:
#Question 2

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

#Drop columns with more than 50% missing values
missing_percent=df.isnull().sum()/len(df)*100
cols_to_drop=missing_percent[missing_percent>50].index
df_clean=df.drop(columns=cols_to_drop)

x=df_clean.drop(columns=['House_Price'])
y=df_clean['House_Price']

num_cols=['Square_Footage','Num_Bedrooms','Num_Bathrooms','Year_Built','Lot_Size','Garage_Size']
cat_cols=['Neighborhood_Quality']

num_imputer=SimpleImputer(strategy="mean")
x[num_cols]=num_imputer.fit_transform(x[num_cols])

if len(cat_cols)>0:
    cat_imputer=SimpleImputer(strategy="most_frequent")
    x[cat_cols]=cat_imputer.fit_transform(x[cat_cols])
    
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

print("X_train shape:",x_train.shape)
print("X_test shape:",x_test.shape)
print("y_train shape:",y_train.shape)
print("y_test shape:",y_test.shape)

X_train shape: (800, 7)
X_test shape: (200, 7)
y_train shape: (800,)
y_test shape: (200,)

---
## Question 3 (20 Marks)

Implement **Simple Linear Regression** using **only NumPy** (no Scikit-Learn allowed):
- Compute slope (`m`) and intercept (`c`) using the Batch Gradient Descent
- Predict values for the test set
- Print the learned `m` and `c` values

Use `Square_Footage` as feature (X) and `House_Price` as target (y).

In [8]:
#Question 3
import numpy as np
x=x_train['Square_Footage'].values
y = y_train.values

x_test_simple=x_test['Square_Footage'].values

x_mean,x_std=np.mean(x),np.std(x)
x_scaled=(x-x_mean)/x_std
x_test_scaled=(x_test_simple-x_mean)/x_std
def compute_cost(x,y,m,c):
    n=len(y)
    y_pred=m*x+c
    cost=(1/n)*np.sum((y_pred-y)**2)
    return cost

def gradient(x,y,m,c):
    n=len(y)
    y_pred=m*x+c
    dw=(2/n)*np.sum((y_pred-y)*x)
    dc=(2/n)*np.sum(y_pred-y)
    return dw, dc
def  gradient_descent(x, y, m_in, c_in, alpha, num_iters):
    m=m_in
    c=c_in
    for i in range(num_iters):
        dw,dc=gradient(x,y,m,c)
        m=m-alpha*dw
        c=c-alpha*dc
        if i % 100 == 0:
         cost=compute_cost(x,y,m,c)
         print(f"Iteration {i},cost:{cost}")
    return m,c
m_init=0.0
c_init=0.0
m_scaled,c_scaled=gradient_descent(x_scaled,y,m_init,c_init,alpha=0.01,num_iters=1000)
m=m_scaled/x_std
c=c_scaled-(m_scaled*x_mean/x_std)

y_pred=m*x_test_simple+c
print("predicted house prices:",y_pred[:5])

print("m:",m)
print("c:",c)

Iteration 0,cost:429162676180.6355
Iteration 100,cost:8655265788.263813
Iteration 200,cost:1259403906.9724996
Iteration 300,cost:1129325883.101059
Iteration 400,cost:1127038077.76263
Iteration 500,cost:1126997839.9644935
Iteration 600,cost:1126997132.2642484
Iteration 700,cost:1126997119.8172543
Iteration 800,cost:1126997119.5983372
Iteration 900,cost:1126997119.594487
predicted house prices: [ 858863.2471529   517515.44329463  998450.8332195  1043375.57356278
  785459.43034201]
m: 200.556876532475
c: 54229.05850461102

---
## Question 4 (10 Marks)

Build a **ColumnTransformer** that applies:
- `StandardScaler` on numerical columns: `Square_Footage`, `Num_Bedrooms`, `Num_Bathrooms`
- `OneHotEncoder` on categorical column: `Neighborhood_Quality`

In [9]:
#Question 4
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

num_cols=['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms']
cat_cols=['Neighborhood_Quality']

preprocessor=ColumnTransformer(
    transformers=[
      ('num',StandardScaler(), num_cols),
      ('cat',OneHotEncoder(),cat_cols)
      ]
)
print(preprocessor)

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['Square_Footage', 'Num_Bedrooms',
                                  'Num_Bathrooms']),
                                ('cat', OneHotEncoder(),
                                 ['Neighborhood_Quality'])])

## Question 5 (20 Marks)

Build a complete **Pipeline** using Scikit-Learn that includes:
- The `ColumnTransformer`
- `SGDRegressor` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [14]:
# Question 5
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error, r2_score
pipeline=Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('regressor',SGDRegressor(max_iter=1000,random_state=42))
    
])
pipeline.fit(x_train,y_train)
y_pred=pipeline.predict(x_test)
rmse=np.sqrt(mean_squared_error(y_test,y_pred))
r2=r2_score(y_test,y_pred)
print(f"RMSE:{rmse}")
print(f"R2 Score:{r2}")

print("First 10 predicted house prices:",y_pred[:10])
print("First 10 actual house prices:",y_test[:10])

RMSE:29096.460915896132
R2 Score:0.9868659781432683
First 10 predicted house prices: [ 851369.90594294  507342.81808969  985831.68390361 1022464.73717754
  759809.07504561  765675.68037077 1004527.78475431  903546.04648129
  797193.07767156  888626.74422641]
First 10 actual house prices: 521    9.010005e+05
737    4.945375e+05
740    9.494042e+05
660    1.040389e+06
411    7.940100e+05
678    7.240336e+05
626    9.984392e+05
513    9.097134e+05
859    7.926815e+05
136    9.474908e+05
Name: House_Price, dtype: float64

---
## Question 6 (20 Marks)

Implement **Multiple Linear Regression** using **Scikit-Learn**:
- The `ColumnTransformer`
- `LinearRegression` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [18]:
# Question 6
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
pipeline_lr=Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('regressor',LinearRegression())
    
])
pipeline_lr.fit(x_train,y_train)
y_pred_lr=pipeline_lr.predict(x_test)
rmse=np.sqrt(mean_squared_error(y_test,y_pred_lr))
r2=r2_score(y_test,y_pred_lr)
print(f"RMSE:{rmse}")
print(f"R2 Score:{r2}")

print("First 10 predicted house prices:",y_pred_lr[:10])
print("First 10 actual house prices:",y_test[:10])

RMSE:29093.075202851724
R2 Score:0.986869034559103
First 10 predicted house prices: [ 851409.14732655  507641.0338697   985990.37503164 1022654.70653384
  760698.13365681  765782.31638091 1005039.09634383  903407.78177236
  797971.18840959  888850.4300377 ]
First 10 actual house prices: 521    9.010005e+05
737    4.945375e+05
740    9.494042e+05
660    1.040389e+06
411    7.940100e+05
678    7.240336e+05
626    9.984392e+05
513    9.097134e+05
859    7.926815e+05
136    9.474908e+05
Name: House_Price, dtype: float64

---
## Question 7 (10 Marks) (You have to explore the topic and use the equation via Numpy)
### Dont use LLMs , You can use Documentation

Implement **Multiple Linear Regression** using **only NumPy**:
- Pick random 100 datas from the dataset
- Use the Normal Equation: `θ = (XᵀX)⁻¹ Xᵀy`
- Use `Square_Footage`, `Num_Bedrooms`, and `Num_Bathrooms` as features
- Print the learned coefficients (θ values)

In [19]:
# Question 7
import numpy as np
df_sample=df.sample(n=100,random_state=42)
print(df_sample)

     Square_Footage  Num_Bedrooms  ...  Neighborhood_Quality   House_Price
521            4012             3  ...                     5  9.010005e+05
737            2310             3  ...                     4  4.945375e+05
740            4708             1  ...                     8  9.494042e+05
660            4932             2  ...                     2  1.040389e+06
411            3646             1  ...                     9  7.940100e+05
..              ...           ...  ...                   ...           ...
436            4992             4  ...                    10  1.068538e+06
764            3458             5  ...                     3  7.607201e+05
88             4145             3  ...                     7  8.982839e+05
63             3842             2  ...                     8  8.632894e+05
826            2836             4  ...                     6  6.053699e+05

[100 rows x 8 columns]

In [20]:
features=['Square_Footage' , 'Num_Bedrooms' ,'Num_Bathrooms']
x_np=df_sample[features].values
y_np=df_sample['House_Price'].values

x_bias=np.c_[np.ones(x_np.shape[0]),x_np]

theta=np.linalg.inv(x_bias.T .dot(x_bias)).dot(x_bias.T).dot(y_np)

print("Learned Coefficients(Theta values):",theta)
print("Intercept:",theta[0])
print("Square Footage Coefficient:",theta[1])
print("Num Bedrooms Coefficient:",theta[2])
print("Num Bathrooms Coefficient:",theta[3])

Learned Coefficients(Theta values): [20888.25945218   202.30820792  8303.2810412   3020.32852173]
Intercept: 20888.259452177677
Square Footage Coefficient: 202.30820792026844
Num Bedrooms Coefficient: 8303.281041200218
Num Bathrooms Coefficient: 3020.3285217270677